version: '3'
services:
  db:
    image: postgres:latest
    container_name: local-database-catalog-music
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: catalog-music
    volumes:
      - ./db:/var/lib/postgresql/data



